### ISSUE TITLE
Error: "Cannot find module 'babel-runtime/helpers/extends'"

### ISSUE THREAD

**Issue by benrolfe** [idangozlan/sequelize-redis#3]
When I require this package, I get an error when I start the server. Am I doing something wrong?

```
const SequelizeRedis = require('sequelize-redis')
```

```
Error: Cannot find module 'babel-runtime/helpers/extends'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/br/Sites/eurolink/api_gateway/node_modules/sequelize-redis/lib/index.js:7:17)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by idangozlan** [comment]
Hi, thanks for the issue, I have no time to make that fix, but If you can contribute and PR a fix for that, it will be great.

**Comment by DuncanMacWeb** [comment]
Hi @idangozlan — could you link to the commit or PR that fixed this, please? I am debugging a similar issue. Thank you.
